version: rv00
type: AutotaggingRunner
optimizer:
  type: SGD
  params:
    learning_rate: 1e-2
    momentum: 0.9
    weight_decay: 1e-6
    nesterov: True
scheduler:
  type: ReduceLROnPlateau
  params:
    mode: 'min'
    factor: 0.2
    patience: 3
    verbose: True
trainer:
  type: Trainer
  params:
    max_epochs: 100
    gpus: [1]
    distributed_backend: dp # train.py: ddp, evaluate.py: dp
    benchmark: False
    deterministic: True